import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./(component)/navbar/page";
import Footer from "./(component)/footer/page";


export const metadata: Metadata = {
  title: "Uber Me",
  description: "Generated by Uber Me",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
       className=" bg-[#F6F7F9]"
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
