import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./(component)/navbar/page";
import Footer from "./(component)/footer/page";

export const metadata: Metadata = {
  title: "Uber Me",
  description: "Generated by Uber Me",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Lexend:wght@400;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="bg-[#F6F7F9] font-lexend">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}